### ISSUE TITLE
Cannot build EntityManagerFactory for other database

### ISSUE THREAD

**Issue by ikenox** [GoogleCloudPlatform/google-cloud-spanner-hibernate#194]
I use `google-cloud-spanner-hibernate-dialect` v1.2.0 in my project, and I want to use also H2 Database in the same project for testing.

But, the following test code fails due to an error `Unable to build Hibernate SessionFactory`.

```java
    @Test
    public void test() {
        Map<String, Object> properties = Map.of(
            AvailableSettings.DRIVER, "org.h2.Driver",
            AvailableSettings.URL, "jdbc:h2:mem:test",
            AvailableSettings.DIALECT, "org.hibernate.dialect.H2Dialect",
            AvailableSettings.HBM2DDL_DATABASE_ACTION, "drop-and-create"
        );
        EntityManagerFactory test = Persistence.createEntityManagerFactory("test", properties);
    }
```

Stacktrace:
```
javax.persistence.PersistenceException: [PersistenceUnit: test] Unable to build Hibernate SessionFactory
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1336)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1262)
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:56)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
        at com.example.H2Test.testSample(H2Test.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassCastException: class org.hibernate.tool.schema.internal.StandardTableExporter cannot be cast to class com.google.cloud.spanner.hibernate.SpannerTableExporter (org.hibernate.tool.schema.internal.StandardTableExporter and com.google.cloud.spanner.hibernate.SpannerTableExporter are in unnamed module of loader 'app')
        at com.google.cloud.spanner.hibernate.schema.SpannerSchemaManagementTool.getSpannerTableExporter(SpannerSchemaManagementTool.java:55)
        at com.google.cloud.spanner.hibernate.schema.SpannerSchemaDropper.doDrop(SpannerSchemaDropper.java:60)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:145)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:316)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259)
        ... 32 more
```

`SpannerSchemaManagementTool`, which is configured by `SpannerServiceContributor`, seems to be always used regardless of database types. The change of #183 maybe related.
Is it possible to use also H2 database in a project which uses `spanner-hibernate-dialect`?

**Comment by dzou** [comment]
Fixed by: https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/208
