### ISSUE TITLE
@NamedQueries with explicit timeout setting

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#85]
Our JDBC driver (not the simba one) seems to set the connection time out to a non-positive value if the timeout setting is used in this annotation. This causes an exception to be thrown. 

For example 
`test_jpql_api_hibernate_named_query_example` in HQLTest.java suffers from this.

**Comment by ChengyuanZhao** [comment]
```
java.lang.IllegalArgumentException: Zero or negative timeout values are not allowed

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.cloud.spanner.connection.ConnectionImpl.setStatementTimeout(ConnectionImpl.java:510)
	at com.google.cloud.spanner.jdbc.AbstractJdbcStatement.resetStatementTimeout(AbstractJdbcStatement.java:117)
	at com.google.cloud.spanner.jdbc.AbstractJdbcStatement.executeQuery(AbstractJdbcStatement.java:137)
	at com.google.cloud.spanner.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:52)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2173)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1936)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
	at org.hibernate.loader.Loader.doQuery(Loader.java:937)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
	at org.hibernate.loader.Loader.doList(Loader.java:2695)
	at org.hibernate.loader.Loader.doList(Loader.java:2678)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2512)
	at org.hibernate.loader.Loader.list(Loader.java:2507)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2263)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1053)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1529)
	at org.hibernate.query.Query.getResultList(Query.java:168)
	at org.hibernate.userguide.sql.SQLTest.lambda$test_sql_hibernate_multiple_scalar_values_dto_hibernate_named_query_example$32(SQLTest.java:643)
	at org.hibernate.testing.transaction.TransactionUtil.doInJPA(TransactionUtil.java:210)
	at org.hibernate.testing.transaction.TransactionUtil.doInJPA(TransactionUtil.java:251)
	at org.hibernate.userguide.sql.SQLTest.test_sql_hibernate_multiple_scalar_values_dto_hibernate_named_query_example(SQLTest.java:638)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.hibernate.testing.junit4.ExtendedFrameworkMethod.invokeExplosively(ExtendedFrameworkMethod.java:45)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ChengyuanZhao** [comment]
```
@NamedQueries({
    @NamedQuery(
        name = "get_phone_by_number",
        query = "select p " +
                "from Phone p " +
                "where p.number = :number",
        timeout = 1,
        readOnly = true
    )
})
```

**Comment by meltsufin** [comment]
@olavloite WDYT?

**Comment by olavloite** [comment]
This should certainly be supported. I've had a quick look at the code in the JDBC driver, and I have a feeling that there's a bug in the JDBC driver causing this. I'll try to create a test case for it and get back to you.

**Comment by dzou** [comment]
Thanks for the quick response Knut.

Here's a code example of this if this would be helpful:
https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/0dfd9b616168557639126fc5e5d7b9d56659ce5f/google-cloud-spanner-hibernate-testing/src/main/java/org/hibernate/userguide/model/Phone.java#L45

**Comment by olavloite** [comment]
It seems that this bug has already been fixed somewhere in the meantime. I've just executed the corresponding test case with the timeout enabled, and it works fine with the newest version of the JDBC driver.

**Comment by dzou** [comment]
@olavloite Thanks for looking into this for us! Yeah looks like this test is now fixed; I'll send out a PR to uncomment the timeout setting.
